# Generated by Django 2.0.7 on 2019-12-30 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(choices=[('black_friday', 'Black Friday'), ('2019_prices', '2019 Prices')], max_length=15, verbose_name='Price Schedule')),
                ('price', models.IntegerField(help_text='Price of product in cents', verbose_name='Product Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name': 'ProductPrice',
                'verbose_name_plural': 'ProductPrices',
            },
        ),
    ]
